/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cloud_logic_custom": [
        {
            "name": "nodeapi",
            "endpoint": "https://nro7wpgb41.execute-api.us-east-1.amazonaws.com/staging",
            "region": "us-east-1"
        },
        {
            "name": "nodeapi2",
            "endpoint": "https://kpoycibwd9.execute-api.us-east-1.amazonaws.com/staging",
            "region": "us-east-1"
        }
    ],
    "aws_cognito_identity_pool_id": "us-east-1:f3c59d55-d8f3-4d85-8bf9-2289ddbf4d90",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_M69d5zI2j",
    "aws_user_pools_web_client_id": "6pqt5u2p7obo0ja7kaifgmrac2",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "erex-codes-storage-98b0492840612-staging",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
